name: Deployment pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1        
      with:
        node-version: '14'
    - name: npm install 
      run: npm install
    - name: run lint
      run: npm run lint
    - name: run jest
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        GUILD_ID: ${{ secrets.GUILD_ID }}
      run: npm test
    - name: run corde
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        GUILD_ID: ${{ secrets.GUILD_ID }}
        CORDE_BOT_TOKEN: ${{ secrets.CORDE_BOT_TOKEN}}
        BOT_TEST_ID: ${{ secrets.BOT_TEST_ID}}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID}}
      run: npm run test:corde
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      # if: ${{ github.event_name == 'push' }} 
      # containerize and push to dockerhub for continuous deployment when a pull request is made to main branch