name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1        
      with:
        node-version: '14'
    - name: npm install 
      run: npm install
    - name: install yarn to run corde
      run: npm install --global yarn
    - name: run corde
      run: npm test