name: Publish Docker image
on:
  pull_request:
    types: [closed]
    branches:
      - main
jobs:
  push_to_registry:
    runs-on: ubuntu-latest

  if: github.event.pull_request.merged
      steps:
        - name: checkout
          if: github.event.pull_request.merged
          uses: actions/checkout@v2
          
  with:
    ref: main

  - name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_URL }}