name: Publish Development Docker image
on:
  workflow_run:
    workflows: ["Testing pipeline"]
    branches: [dev]
    types: 
      - completed
jobs:
  Push_to_registry:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          ref: dev
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_TEST_URL }}