name: Testing pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  testing_pipeline:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1        
      with:
        node-version: '14'
    - name: npm install 
      run: npm install
    - name: run lint
      run: npm run lint
    - name: run jest and corde test with nyc
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        GUILD_ID: ${{ secrets.GUILD_ID }}
        CORDE_BOT_TOKEN: ${{ secrets.CORDE_BOT_TOKEN}}
        BOT_TEST_ID: ${{ secrets.BOT_TEST_ID}}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID}}
      run: npm test
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1